Fluent/Chain of invocations Homework
MaluLePoulet/AQA27Onl pull request #9
Opened 2024-08-29 17:36 UTC by MaluLePoulet

Created a test scenario <Add Project> using Fluent/Chain of invocations Pattern

2024-09-10 10:15 UTC, wildpioneer requested changes

2024-09-10 10:15 UTC, wildpioneer commented on src/test/java/pages/LoginPage.java
> +    public void clickLogin() {
А почему тут void?

2024-09-10 10:15 UTC, wildpioneer commented on src/test/java/pages/DashboardPage.java
> +    public void openPageByUrl() {
Тоже - почему void?

2024-09-15 17:05 UTC, MaluLePoulet commented on src/test/java/pages/LoginPage.java
> +    public void clickLogin() {
Исправила

2024-09-15 17:05 UTC, MaluLePoulet commented on src/test/java/pages/DashboardPage.java
> +    public void openPageByUrl() {
Исправила

2025-02-20 14:25 UTC, closed without merging